CREATE TABLE `beneficiaries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`submissionId` int NOT NULL,
	`gender` enum('male','female') NOT NULL,
	`age` int NOT NULL,
	`prefix` varchar(50) NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`percentage` decimal(5,2) NOT NULL,
	`relationship` varchar(100) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `beneficiaries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `insurance_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`agentCode` varchar(50) NOT NULL DEFAULT '',
	`prefix` varchar(20) NOT NULL DEFAULT '',
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`nickname` varchar(100),
	`phone` varchar(20) NOT NULL,
	`email` varchar(320) NOT NULL,
	`occupation` varchar(200) NOT NULL,
	`position` varchar(200) NOT NULL,
	`height` decimal(5,1) NOT NULL,
	`weight` decimal(5,1) NOT NULL,
	`annualIncome` decimal(15,2) NOT NULL,
	`idCardStatus` enum('sent','not_sent') NOT NULL DEFAULT 'not_sent',
	`idCardImageUrl` text,
	`maritalStatus` enum('single','married','divorced','widowed') NOT NULL DEFAULT 'single',
	`spouseFirstName` varchar(100),
	`spouseLastName` varchar(100),
	`spouseBirthDate` varchar(20),
	`useIdCardAddress` int NOT NULL DEFAULT 0,
	`addressLine` text,
	`subDistrict` varchar(100),
	`district` varchar(100),
	`province` varchar(100),
	`postalCode` varchar(10),
	`benefitPaymentMethod` enum('bank_account','promptpay') NOT NULL,
	`bankName` varchar(100),
	`bankAccountNumber` varchar(50),
	`policyDelivery` enum('e_document','paper_customer','paper_agent') NOT NULL,
	`paymentMethod` enum('qr_transfer','credit_debit') NOT NULL,
	`hasExistingInsurance` int NOT NULL DEFAULT 0,
	`existingInsuranceCompany` varchar(200),
	`hasLifeInsurance` int NOT NULL DEFAULT 0,
	`hasCriticalIllness` int NOT NULL DEFAULT 0,
	`hasAccidentRider` int NOT NULL DEFAULT 0,
	`hasHospitalDaily` int NOT NULL DEFAULT 0,
	`existingPolicyActive` enum('active','inactive'),
	`wasPreviouslyRejected` int NOT NULL DEFAULT 0,
	`rejectedCompany` varchar(200),
	`rejectedReason` varchar(500),
	`rejectedDate` varchar(20),
	`submissionRef` varchar(20) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `insurance_submissions_id` PRIMARY KEY(`id`),
	CONSTRAINT `insurance_submissions_submissionRef_unique` UNIQUE(`submissionRef`)
);
